spring:
  profiles:
    active: peer1
---
spring:
  application:
    name: eureka-service
  profiles: peer1
server:
  port: ${PORT:8761}
eureka:
 instance:
  hostname: peer1
  preferIpAddress: true
  leaseExpirationDurationInSeconds: 90
  leaseRenewalIntervalInSeconds: 30
  metadataMap:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
---
spring:
  application:
    name: eureka-service
  profiles: peer2
server:
  port: ${PORT:8761}
eureka:
 instance:
  hostname: peer2
  preferIpAddress: true
  leaseExpirationDurationInSeconds: 90
  leaseRenewalIntervalInSeconds: 30
  metadataMap:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
