spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password:
    initialize: true
server:
  port: ${PORT:8080}
  contextPath: /
#message : im changed~~
message : goodbye 2016 and hello 2017
---
spring:
  profiles: product
  datasource:
    url: jdbc:oracle:thin:@ip:port:sid
    username: username
    password: password
server:
  port: ${PORT:8080}
  contextPath: /
message : hello~
